swagger: '2.0'
info: {title: Power BI REST API, description: Power BI REST API, version: '1.3'}
host: api.powerbi.com
basePath: /
schemes: [https]
consumes: []
produces: []
paths:
  /v1.0/myorg/groups/{groupId}/dataflows/{dataflowId}/refreshes:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: Refresh Dataflow
      description: Refresh one defined Dataflow
      operationId: RefreshDataflow
      parameters:
      - {name: groupId, in: path, required: true, type: string}
      - {name: dataflowId, in: path, required: true, type: string}
      - {name: 'Content-Type:', in: header, required: false, type: string}
      - name: body
        in: body
        required: false
        schema:
          type: object
          properties:
            refreshRequest: {type: string, description: refreshRequest}
            notifyOption: {type: string, description: notifyOption}
definitions: {}
parameters: {}
responses: {}
securityDefinitions:
  oauth2_auth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://login.windows.net/common/oauth2/authorize
    tokenUrl: https://login.windows.net/common/oauth2/authorize
    scopes: {}
security:
- oauth2_auth: []
tags: []